Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -14,7 +14,7 @@ jobs:
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Build Docker Image
         run: |
@@ -22,11 +22,11 @@ jobs:
 
       - name: Run Container and Save Output
         run: |
-          docker run --rm print-args-env
-          docker cp $(docker create --rm print-args-env):/app/output.txt output.txt || echo "Failed to copy output"
+          docker run --rm --name print-args-container print-args-env
+          docker cp print-args-container:/app/output.txt output.txt || echo "Failed to copy output"
 
       - name: Upload Output as Artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: output-file
           path: output.txt
